name: CICD

on:
  push:

jobs:
  deploy:
    if:   github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup AWS Copilot
        run: |
          sudo curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux \
             && sudo chmod +x /usr/local/bin/copilot \
             && copilot --help
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: copilot deploy prod
        run: |
          copilot deploy prod

  # docker:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: ghcr.io/peter-testing-org/fa_github_event_notifier:${{ github.sha }}
  #         labels: |
  #           org.opencontainers.image.source=https://github.com/${{ github.repository }}
  #           org.opencontainers.image.version=${{ github.sha }}
  #           org.opencontainers.image.revision=${{ github.sha }}
  #           org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.sha }}
  #           org.opencontainers.image.vendor=PeterSingh
