name: CICD

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host kamal-test
              HostName ec2-52-211-154-39.eu-west-1.compute.amazonaws.com
              User root
              IdentityFile ~/.ssh/id_rsa

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # bundle install
      - env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bin/kamal deploy

      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: ghcr.io/peter-testing-org/fa_github_event_notifier:${{ github.sha }}
      #     labels: |
      #       org.opencontainers.image.source=https://github.com/${{ github.repository }}
      #       org.opencontainers.image.version=${{ github.sha }}
      #       org.opencontainers.image.revision=${{ github.sha }}
      #       org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/${{ github.sha }}
      #       org.opencontainers.image.vendor=PeterSingh
